# Generated by Django 3.0.5 on 2020-04-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
